### ISSUE TITLE
Fails when there are unescaped parenthesis "(500) days of summer (2009)"

### ISSUE THREAD

**Issue by tanmayrajani** [tanmayrajani/cinephi1e#8]
It stops responding after getting this error. Following is the error log:
```
2017-04-23T07:04:07.425346+00:00 app[web.1]: Msg text: "(500) days of summer (2009)"
2017-04-23T06:57:47.234810+00:00 app[web.1]: SyntaxError: Invalid regular expression: /^(/: Unterminated group
2017-04-23T06:57:47.234812+00:00 app[web.1]:     at new RegExp (native)
2017-04-23T06:57:47.234813+00:00 app[web.1]:     at SoundEx.process (/app/node_modules/natural/lib/natural/phonetics/sou
ndex.js:72:39)
2017-04-23T06:57:47.234813+00:00 app[web.1]:     at compare (/app/node_modules/natural/lib/natural/phonetics/phonetic.js
:29:21)
2017-04-23T06:57:47.234814+00:00 app[web.1]:     at changeTextNatural (/app/index.js:135:58)
2017-04-23T06:57:47.234814+00:00 app[web.1]:     at /app/index.js:431:41
2017-04-23T06:57:47.234815+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/rout
er/layer.js:95:5)
2017-04-23T06:57:47.234816+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2017-04-23T06:57:47.234816+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)

2017-04-23T06:57:47.234817+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/rout
er/layer.js:95:5)
2017-04-23T06:57:47.234818+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:281:22
```

**Comment by bbackspace** [comment]
I tried replicating but wasn't able to reproduce this. Then looking at the commit history, this seems to be fixed.

**Comment by tanmayrajani** [comment]
Yes, had fixed it on the next day.. Forgotten to update issue. Thanks.
